# Generated by Django 3.2.9 on 2021-11-11 16:49

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('is_alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedUser',
            fields=[
                ('person_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('scrap_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('texted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('token', models.CharField(default=core.utils.get_token, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('guild_invite', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_data', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('dm_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scrapeduser')),
                ('dm_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='scrapeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_users', to='core.user'),
        ),
        migrations.CreateModel(
            name='RestrictedRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('text_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.usermessagedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('invite_info', models.CharField(max_length=128)),
                ('guild_invite', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='core.scrapeduser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='core.user'),
        ),
    ]
