# Generated by Django 3.2.9 on 2021-11-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeduser',
            name='scrap_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usermessagedata',
            name='channel',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usermessagedata',
            name='guild',
            field=models.BigIntegerField(),
        ),
    ]
